import { Metadata } from 'next';
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: 'Next.js',
    template: '%s | Codevolution'
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Header</p>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
